/*
 * zs_CmdList.h
 *
 *  Created on: 2016-10-14
 *      Author: yst
 */

#ifndef ZS_CMDLIST_H_
#define ZS_CMDLIST_H_

//传输命令
#define	COMMAND_TRANS_ORIDATA									0
#define	COMMAND_TRANS_MTSFILE									(COMMAND_TRANS_ORIDATA+1)
#define	COMMAND_TRANS_MTSPARA									(COMMAND_TRANS_MTSFILE+1)
#define	COMMAND_TRANS_REALTIME_MTINFO_START						(COMMAND_TRANS_MTSPARA+1)
#define	COMMAND_TRANS_REALTIME_MTINFO_STOP						(COMMAND_TRANS_REALTIME_MTINFO_START+1)
#define COMMAND_VIRTUAL_KEYBOARD								(COMMAND_TRANS_REALTIME_MTINFO_STOP+1)
#define	COMMAND_SNAP_ALL_MTDATA									(COMMAND_VIRTUAL_KEYBOARD+1)//测温截图，原始数据及测温信息，与模拟视频一致的JPG文件
#define	COMMAND_REALTIME_OBJECT_MTINFO							(COMMAND_SNAP_ALL_MTDATA+1)//实时测温，包括点，线，区域等对象，可控制传输开启与关闭

////////////////////////////////////////////////
#define COMMAND_SET_IMG_MODE									(COMMAND_REALTIME_OBJECT_MTINFO + 1)	// 图像模式
#define COMMAND_SET_IMG_EFFECT									(COMMAND_SET_IMG_MODE + 1)              // 图像效果
#define COMMAND_SET_IMG_GAIN									(COMMAND_SET_IMG_EFFECT + 1)			// 图像增益
#define COMMAND_SET_IMG_BRIGHT									(COMMAND_SET_IMG_GAIN + 1)          	// 图像亮度
#define COMMAND_SET_KEYBOARD_STOP								(COMMAND_SET_IMG_BRIGHT + 1) //虚拟键盘停


///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//原始数据用到  50hz 高铁
#define	COMMAND_IMG_CRT_PROCESS									(COMMAND_SET_IMG_BRIGHT + 1)			//数据校正处理
#define	COMMAND_DO_BP_PROCESS									(COMMAND_IMG_CRT_PROCESS + 1)			//盲元处理
#define	COMMAND_CONNECT_INIT									(COMMAND_DO_BP_PROCESS + 1)				//网络连接时，初始化工作

//两点校正
#define COMMAND_TPC_SAMPLE_HIGH_DATA                            (COMMAND_CONNECT_INIT+1)				//两点校正    采集高温数据
#define COMMAND_TPC_SAMPLE_LOW_DATA                             (COMMAND_TPC_SAMPLE_HIGH_DATA+1)		//两点校正    采集低温数据
#define COMMAND_TPC_SAMPLE_DO_CHECK                             (COMMAND_TPC_SAMPLE_LOW_DATA+1)			//两点校正    校正
#define COMMAND_TPC_SAMPLE_SAVE_DATA							(COMMAND_TPC_SAMPLE_DO_CHECK+1)			//两点校正    保存校正数据
#define COMMAND_TPC_SAMPLE_CLEAR_DATA                           (COMMAND_TPC_SAMPLE_SAVE_DATA+1)		//两点校正    保存校正数据

//盲元处理
#define COMMAND_BP_REPLACE_POINT	                            (COMMAND_TPC_SAMPLE_CLEAR_DATA+1)		//盲元处理    打点
#define COMMAND_BP_REPLACE_H_LINE	                            (COMMAND_BP_REPLACE_POINT+1)		    //盲元处理    打横线
#define COMMAND_BP_REPLACE_V_LINE	                            (COMMAND_BP_REPLACE_H_LINE+1)			//盲元处理    打竖线
#define COMMAND_BP_SET_THERSOLD_V	                            (COMMAND_BP_REPLACE_V_LINE+1)		    //盲元处理    设定阈值
#define COMMAND_BP_AUTO_REPLACE									(COMMAND_BP_SET_THERSOLD_V+1)			//盲元处理    自动
#define COMMAND_BP_DATA_SAVE									(COMMAND_BP_AUTO_REPLACE+1)				//盲元处理    盲元数据清除
#define COMMAND_BP_DATA_CLEAR									(COMMAND_BP_DATA_SAVE+1)				//盲元处理    盲元数据保存
#define COMMAND_BP_CURSOR_SHOW_CTRL	                            (COMMAND_BP_DATA_CLEAR+1)				//盲元处理    光标显示控制

//数据采集
#define COMMAND_MT_SAMPLE_SET_L_POS					(COMMAND_BP_CURSOR_SHOW_CTRL+1)						//数据采集    设置低温黑体坐标
#define COMMAND_MT_SAMPLE_SET_H_POS					(COMMAND_MT_SAMPLE_SET_L_POS+1)						//数据采集    设置低温黑体坐标
#define COMMAND_MT_SAMPLE_SET_C_POS					(COMMAND_MT_SAMPLE_SET_H_POS+1)						//数据采集    设置低温黑体坐标
#define COMMAND_MT_SAMPLE_SET_L_TEMP	            (COMMAND_MT_SAMPLE_SET_C_POS+1)						//数据采集    设置低温黑体坐标
#define COMMAND_MT_SAMPLE_SET_H_TEMP	            (COMMAND_MT_SAMPLE_SET_L_TEMP+1)					//数据采集    设置低温黑体坐标
#define COMMAND_MT_SAMPLE_SET_C_TEMP	            (COMMAND_MT_SAMPLE_SET_H_TEMP+1)					//数据采集    设置低温黑体坐标
#define COMMAND_MT_SAMPLE_SET_OPEN_CTRL	            (COMMAND_MT_SAMPLE_SET_C_TEMP+1)					//数据采集    采集开启控制
#define COMMAND_MT_SAMPLE_SET_DATA_SAVE	            (COMMAND_MT_SAMPLE_SET_OPEN_CTRL+1)					//数据采集    采集数据保存
#define COMMAND_MT_SAMPLE_SET_CURSOR_CTRL	        (COMMAND_MT_SAMPLE_SET_DATA_SAVE+1)					//数据采集    光标显示控制
#define COMMAND_MT_SAMPLE_SET_OUT_PARAM_SAVE	    (COMMAND_MT_SAMPLE_SET_CURSOR_CTRL+1)				//数据采集    从DSP导出数据
#define COMMAND_MT_SAMPLE_SET_DATA_CLEAR	    (COMMAND_MT_SAMPLE_SET_OUT_PARAM_SAVE+1)			//数据采集    导入数据到DSP

//图像设置
#define COMMAND_IMG_NORMAL_SET_E_ZOOM	            (COMMAND_MT_SAMPLE_SET_DATA_CLEAR+1)			//图像设置    电子变倍
#define COMMAND_IMG_NORMAL_SET_MODE	                (COMMAND_IMG_NORMAL_SET_E_ZOOM+1)					//图像设置    图像模式
#define COMMAND_IMG_NORMAL_SET_TDF	                (COMMAND_IMG_NORMAL_SET_MODE+1)						//图像设置    时域滤波
#define COMMAND_IMG_NORMAL_SET_SDF	                (COMMAND_IMG_NORMAL_SET_TDF+1)						//图像设置    空域滤波
#define COMMAND_IMG_NORMAL_SET_IDE	                (COMMAND_IMG_NORMAL_SET_SDF+1)						//图像设置    IDE
#define COMMAND_IMG_NORMAL_SET_GAIN	                (COMMAND_IMG_NORMAL_SET_IDE+1)						//图像设置    增益
#define COMMAND_IMG_NORMAL_SET_BRIGHT	            (COMMAND_IMG_NORMAL_SET_GAIN+1)						//图像设置    对比度
#define COMMAND_IMG_NORMAL_SET_CR	                (COMMAND_IMG_NORMAL_SET_BRIGHT+1)					//图像设置    伪彩色
#define COMMAND_IMG_NORMAL_SET_MIRROR	            (COMMAND_IMG_NORMAL_SET_CR+1)						//图像设置    镜像
#define COMMAND_IMG_NORMAL_SET_BCK_DEF	            (COMMAND_IMG_NORMAL_SET_MIRROR+1)					//图像设置    恢复默认
#define COMMAND_IMG_NORMAL_SET_SAVE	                (COMMAND_IMG_NORMAL_SET_BCK_DEF+1)					//图像设置    保存

//电位计
#define COMMAND_AF_SET_FAR_POS	                (COMMAND_IMG_NORMAL_SET_SAVE+1)							//自动聚焦    远焦位置
#define COMMAND_AF_SET_NEAR_POS	                (COMMAND_AF_SET_FAR_POS+1)								//自动聚焦    近焦位置
#define COMMAND_AF_SET_POT_ENABLE_CTRL	        (COMMAND_AF_SET_NEAR_POS+1)								//自动聚焦    电位计使能控制
#define COMMAND_AF_GET_POT_CUR_POS	            (COMMAND_AF_SET_POT_ENABLE_CTRL+1)						//自动聚焦    当前位置
#define COMMAND_AF_SET_SAVE						(COMMAND_AF_GET_POT_CUR_POS+1)							//自动聚焦    保存
#define COMMAND_AF_SET_FAR_CALL	                (COMMAND_AF_SET_SAVE+1)									//自动聚焦    远焦调用
#define COMMAND_AF_SET_NEAR_CALL	            (COMMAND_AF_SET_FAR_CALL+1)								//自动聚焦    近郊调用


//维护
#define COMMAND_MAINTAIN_BCK_FACTORY            (COMMAND_AF_SET_NEAR_CALL+1)							//维护    恢复出厂
#define COMMAND_MAINTAIN_BCK_IMG_DEF            (COMMAND_MAINTAIN_BCK_FACTORY+1)						//维护    图像恢复默认
#define COMMAND_MAINTAIN_SAVE_ALL               (COMMAND_MAINTAIN_BCK_IMG_DEF+1)						//维护    保存所有参数
#define COMMAND_MAINTAIN_REBOOT					(COMMAND_MAINTAIN_SAVE_ALL+1)							//维护    设备重启

#define COMMAND_SET_HIGH_TEMPRETURE_VPT_A_GRAY	(COMMAND_MAINTAIN_REBOOT+1)
#define COMMAND_SET_HIGH_TEMPRETURE_DEF			(COMMAND_SET_HIGH_TEMPRETURE_VPT_A_GRAY+1)
#define COMMAND_SET_HIGH_TEMPRETURE_SAVE		(COMMAND_SET_HIGH_TEMPRETURE_DEF+1)




#define	COMMAND_TRANS_END										10000


//设置命令
#define	COMMAND_SET_POINT										(COMMAND_TRANS_END+1)
#define	COMMAND_SET_RECT										(COMMAND_SET_POINT+1)
#define	COMMAND_SET_LINE										(COMMAND_SET_RECT+1)

#define	COMMAND_SET_COLORRULE									(COMMAND_SET_LINE+1)
#define	COMMAND_AGC_MODE										(COMMAND_SET_COLORRULE+1)
#define COMMAND_SC_MODE											(COMMAND_AGC_MODE+1)
#define COMMAND_BRIGHT_ADJUST									(COMMAND_SC_MODE+1)
#define COMMAND_COLORRULE_SELECT								(COMMAND_BRIGHT_ADJUST+1)
#define	COMMAND_DOZERO											(COMMAND_COLORRULE_SELECT+1)
#define	COMMAND_EMISSIVITY										(COMMAND_DOZERO+1)//
#define	COMMAND_BK_TEMPER										(COMMAND_EMISSIVITY+1)//
#define	COMMAND_AMBIENT_TEMPER									(COMMAND_BK_TEMPER+1)//
#define	COMMAND_DISTANT											(COMMAND_AMBIENT_TEMPER+1)//
#define	COMMAND_HUMIDITY										(COMMAND_DISTANT+1)//
#define	COMMAND_GUI_LAYOUT_SET									(COMMAND_HUMIDITY + 1)  //界面布局切换
#define	COMMAND_AUTO_FOCUS									    (COMMAND_GUI_LAYOUT_SET + 1) //自动聚焦
#define	COMMAND_SET_POINT_ALARM_INFO							(COMMAND_AUTO_FOCUS+1)//
#define	COMMAND_SET_LINE_ALARM_INFO								(COMMAND_SET_POINT_ALARM_INFO+1)//
#define	COMMAND_SET_RECT_ALARM_INFO								(COMMAND_SET_LINE_ALARM_INFO+1)//
#define	COMMAND_SET_USER_TEMPER_REVISE							(COMMAND_SET_RECT_ALARM_INFO+1)//温度补偿
#define	COMMAND_SET_CLEAR_ALL_MT_OBJ							(COMMAND_SET_USER_TEMPER_REVISE+1)
#define	COMMAND_SET_SAVE_COLOR_RULER							(COMMAND_SET_CLEAR_ALL_MT_OBJ+1)
#define	COMMAND_SET_HIGH_TEMP_PROTECT							(COMMAND_SET_SAVE_COLOR_RULER+1)
#define	COMMAND_SET_FOCUS_NEAR									(COMMAND_SET_HIGH_TEMP_PROTECT+1)
#define	COMMAND_SET_FOCUS_FAR									(COMMAND_SET_FOCUS_NEAR+1)
#define	COMMAND_SET_MT_PARA_SAVE								(COMMAND_SET_FOCUS_FAR+1)  //将参数保存到FLASH，
#define	COMMAND_SET_POINT_ATTRIBUTE								(COMMAND_SET_MT_PARA_SAVE+1)  //设置点 局部参数
#define	COMMAND_SET_POINT_POSITION								(COMMAND_SET_POINT_ATTRIBUTE+1) //设置点 位置
#define	COMMAND_SET_RECT_ATTRIBUTE								(COMMAND_SET_POINT_POSITION+1)  //设置矩形 局部参数
#define	COMMAND_SET_RECT_POSITION								(COMMAND_SET_RECT_ATTRIBUTE+1) //设置矩形 位置
#define	COMMAND_SET_LINE_ATTRIBUTE								(COMMAND_SET_RECT_POSITION+1) //设置线 局部参数
#define	COMMAND_SET_LINE_POSITION								(COMMAND_SET_LINE_ATTRIBUTE+1) //设置线 位置

#define	COMMAND_GET_DSP1_INFO									(COMMAND_SET_LINE_POSITION+1)
#define	COMMAND_SET_START_MT_DATA_COLLECT						(COMMAND_GET_DSP1_INFO+1)   //开始数据采集
#define	COMMAND_SET_SAVE_MT_DATA_COLLECT						(COMMAND_SET_START_MT_DATA_COLLECT+1) //保存数据采集
#define	COMMAND_SET_STOP_MT_DATA_COLLECT						(COMMAND_SET_SAVE_MT_DATA_COLLECT+1) //停止数据采集
#define	COMMAND_SET_IMAGE_DDE									(COMMAND_SET_STOP_MT_DATA_COLLECT+1) //图像细节增强
#define	COMMAND_SET_IMAGE_ALARM_INFO							(COMMAND_SET_IMAGE_DDE + 1)     //设置图像报警信息
#define	COMMAND_SET_MT_STALL									(COMMAND_SET_IMAGE_ALARM_INFO+1) //设置测温档位
#define	COMMAND_SET_MT_RESET_ALL_PARAMETER						(COMMAND_SET_MT_STALL+1)  //重置所有
#define	COMMAND_SET_MT_TRANSMITTANCE_COFF						(COMMAND_SET_MT_RESET_ALL_PARAMETER+1) //通过率
#define COMMAND_SET_MT_ALL_PARAMETER							(COMMAND_SET_MT_TRANSMITTANCE_COFF+1)  //统一设置所有参数 ?
#define COMMAND_SET_HIGH_TEMPRETURE_PROTECT						(COMMAND_SET_MT_ALL_PARAMETER+1)  //高温保护
#define COMMAND_SET_HIGH_TEMPRETURE_FRESET						(COMMAND_SET_HIGH_TEMPRETURE_PROTECT+1) //挡片弹起
#define COMMAND_SET_TEMPRETURE_EQUAL							(COMMAND_SET_HIGH_TEMPRETURE_FRESET+1) //设置等温显示
#define COMMAND_SET_TEMPRETURE_SECTION							(COMMAND_SET_TEMPRETURE_EQUAL+1) //设置分段拉伸
#define COMMAND_SET_SWITCH_PROTOL_THERMEYE_TO_QUANTUM           (COMMAND_SET_TEMPRETURE_SECTION+1) //THERMEYE_TO_QUANTUM
#define COMMAND_SET_ALARM_IO_OUT_SWITCH							(COMMAND_SET_SWITCH_PROTOL_THERMEYE_TO_QUANTUM+1) //设置IO报警开关
#define COMMAND_SET_UART2_OUTPUT                                (COMMAND_SET_ALARM_IO_OUT_SWITCH +1)
#define COMMAND_SET_AUTO_SHUTTER_SWITCH							(COMMAND_SET_UART2_OUTPUT+1) //自动调零开关
#define COMMAND_SET_AUTO_IMAGE_MODE								(COMMAND_SET_AUTO_SHUTTER_SWITCH+1)//设置图像模式  0 默认模式  1 hdr  2 天地  3 普通
#define COMMAND_SET_REBOOT_DSP									(COMMAND_SET_AUTO_IMAGE_MODE+1)//后端重启dsp

//DSP测试  输I/O口  报警 输入
#define COMMAND_SET_TEST_ALARM_IN								(COMMAND_SET_REBOOT_DSP			 + 1)
#define COMMAND_SET_TEST_ALARM_OUT								(COMMAND_SET_TEST_ALARM_IN 		 + 1)
#define COMMAND_SET_TEST_MOTOR_AF								(COMMAND_SET_TEST_ALARM_OUT 	 + 1)   //调焦电机
#define COMMAND_SET_TEST_MOTOR_LENS								(COMMAND_SET_TEST_MOTOR_AF 	     + 1)   //变焦电机

#define COMMAND_SET_INTELLIGENT_ANALYSIS                        (COMMAND_SET_TEST_MOTOR_LENS + 1)
#define COMMAND_ENABLE_INTELLIGENT_ANALYSIS                     (COMMAND_SET_INTELLIGENT_ANALYSIS + 1)
#define COMMAND_SAVE_INTELLIGENT_ANALYSIS                       (COMMAND_ENABLE_INTELLIGENT_ANALYSIS + 1)
#define COMMAND_GET_INTELLIGENT_ANALYSIS						(COMMAND_SAVE_INTELLIGENT_ANALYSIS + 1)
#define COMMAND_INTELLIGENT_ANALYSIS_AREA_SHOW                  (COMMAND_GET_INTELLIGENT_ANALYSIS + 1)

#define COMMAND_SET_IDE_VALUE (COMMAND_INTELLIGENT_ANALYSIS_AREA_SHOW + 1) //设置IDE，附加值char ，0～10
#define COMMAND_SET_MIRRORING (COMMAND_SET_IDE_VALUE + 1) //设置镜像，附加值char， 0：关闭； 1：左右； 2上下； 3：中心
#define COMMAND_SET_FUNCTION_HT_ALARM_PARA 						(COMMAND_SET_MIRRORING + 1) //功能设置中的高温报警参数设置

#define COMMAND_SET_PRESET_POINT 								(COMMAND_SET_FUNCTION_HT_ALARM_PARA+1)					 //预置点
#define COMMAND_SET_PRESET_POINT_CHANGE 					    (COMMAND_SET_PRESET_POINT+1)			     //预置位 已变动 0 1

#define COMMAND_SET_DFOV_FOV_SWITCH 							(COMMAND_SET_PRESET_POINT_CHANGE+1)   //视场切换
#define COMMAND_SET_DFOV_BEST_POS_USE 							(COMMAND_SET_DFOV_FOV_SWITCH+1)   //最佳位置使用
#define COMMAND_SET_DFOV_BEST_POS_SAVE 							(COMMAND_SET_DFOV_BEST_POS_USE+1)  //记忆最佳位置使用
#define COMMAND_SET_DFOV_PARAM_SAVE 							(COMMAND_SET_DFOV_BEST_POS_SAVE+1) //DFOV保存

#define COMMAND_SET_CMOS_RESTART       (COMMAND_SET_DFOV_PARAM_SAVE+1) //CMOS车输出重新开始
#define COMMAND_SET_DSP_FACTORY_SET	   (COMMAND_SET_CMOS_RESTART+1)    //dsp端 恢复出厂设置  并保存

#define COMMAND_SET_DSP_ZOOM_TYPE_SET  (COMMAND_SET_DSP_FACTORY_SET+1) //dsp端 设置变倍类型    0先光学后电子变倍  1光学变倍 2电子变倍

#define COMMAND_SET_DSP_ZOOM_LARGE								(COMMAND_SET_DSP_ZOOM_TYPE_SET+1) //光学变倍大
#define COMMAND_SET_DSP_ZOOM_SHRINK								(COMMAND_SET_DSP_ZOOM_LARGE+1) //光学变倍小
#define COMMAND_SET_DSP_ZOOM_LARGE_STOP_WITH_AUTOFOCUS			(COMMAND_SET_DSP_ZOOM_SHRINK+1) //光学变倍大，停止时触发自动聚焦
#define COMMAND_SET_DSP_ZOOM_SHRINK_STOP_WITH_AUTOFOCUS			(COMMAND_SET_DSP_ZOOM_LARGE_STOP_WITH_AUTOFOCUS+1)//光学变倍小，停止时触发自动聚焦
#define COMMAND_SET_DSP_LANGUAGE								(COMMAND_SET_DSP_ZOOM_SHRINK_STOP_WITH_AUTOFOCUS+1)//设置dsp菜单语言
#define COMMAND_SET_DSP_ACCURACY								(COMMAND_SET_DSP_LANGUAGE+1)//设置测温精度
#define COMMAND_SET_DSP_IMAGE_PARA								(COMMAND_SET_DSP_ACCURACY+1)//设置图像参数
#define COMMAND_SET_DSP_FOCUS_INFO								(COMMAND_SET_DSP_IMAGE_PARA+1)//设置聚焦镜头参数
#define COMMAND_SET_DSP_ZOOM_INFO								(COMMAND_SET_DSP_FOCUS_INFO+1)//设置变倍镜头参数
#define COMMAND_SET_DSP_HT_PROTECT								(COMMAND_SET_DSP_ZOOM_INFO+1)//设置高温保护参数

#define COMMAND_SET_DSP_SET_MOTO_PRESET							(COMMAND_SET_DSP_HT_PROTECT+1)//设置预置位
#define COMMAND_SET_DSP_GOTO_MOTO_PRESET						(COMMAND_SET_DSP_SET_MOTO_PRESET+1)//调用预置位
#define COMMAND_SET_DSP_CLEAR_MOTO_PRESET						(COMMAND_SET_DSP_GOTO_MOTO_PRESET+1)//删除预置位
#define COMMAND_SET_DSP_SHOW_GRAY_POT							(COMMAND_SET_DSP_CLEAR_MOTO_PRESET+1)//一键显示电位计和灰度 熊力红用
#define COMMAND_SET_DSP_CROSS_PARA								(COMMAND_SET_DSP_SHOW_GRAY_POT+1)//设置十字光标属性
#define COMMAND_SET_GET_CONFIG_PARA								(COMMAND_SET_DSP_CROSS_PARA+1)//获取菜单配置参数
#define COMMAND_SET_DSP_HT_ALARM_PARA							(COMMAND_SET_GET_CONFIG_PARA+1)//功能设置中的高温报警参数设置

#define COMMAND_SET_DSP_EZOOM_LARGE								(COMMAND_SET_DSP_HT_ALARM_PARA+1)//电子变倍大
#define COMMAND_SET_DSP_EZOOM_SHRINK							(COMMAND_SET_DSP_EZOOM_LARGE+1)//电子变倍小
#define COMMAND_SET_DSP_LENSZOOM_EZOOM_LARGE					(COMMAND_SET_DSP_EZOOM_SHRINK+1)//先光学变倍大  再电子变倍 有电位计的情况下才会自动切换 无电位计只能光学变倍
#define COMMAND_SET_DSP_LENSZOOM_EZOOM_SHRINK					(COMMAND_SET_DSP_LENSZOOM_EZOOM_LARGE+1)//先电子变倍小  再光学变倍小 有电位计的情况下才会自动切换 无电位计只能光学变倍

#define COMMAND_SET_INTELLIGENT_ANALYSIS_MD_GLOBAL_EN           (COMMAND_SET_DSP_LENSZOOM_EZOOM_SHRINK+1)//智能分析 移动侦测全局使能
#define COMMAND_SET_INTELLIGENT_ANALYSIS_IO_ALAM_EN             (COMMAND_SET_INTELLIGENT_ANALYSIS_MD_GLOBAL_EN+1)  //智能分析 DSP IO报警使能

#define COMMAND_SET_DSP_TEMPERATURE_UNIT             			(COMMAND_SET_INTELLIGENT_ANALYSIS_IO_ALAM_EN+1)  //设置温度单位  0摄氏度 1华氏度 2开氏度

#define COMMAND_SET_DSP_MD_SENSI_SET                            (COMMAND_SET_DSP_TEMPERATURE_UNIT+1)   //设置灵敏度

#define COMMAND_SET_DSP_HTP_STALL_SWITCH	(COMMAND_SET_DSP_MD_SENSI_SET+1)//设置高温保护光栏片弹起0/挡下1 再停止
#define COMMAND_SET_DSP_HTP_SWITCH			(COMMAND_SET_DSP_HTP_STALL_SWITCH+1)//设置高温保护功能关闭0/开启1

#define COMMAND_SET_ABS_FOCUS_LENS_POS							(COMMAND_SET_DSP_HTP_SWITCH+1)//设置聚焦镜头的绝对位置，U16
#define COMMAND_SET_ABS_ZOOM_LENS_POS							(COMMAND_SET_ABS_FOCUS_LENS_POS+1)//设置变倍镜头的绝对位置，U16
#define COMMAND_SET_DO_ZERO_TIME_INTERVAL						(COMMAND_SET_ABS_ZOOM_LENS_POS+1)//设置自动调零的时间间隔
#define COMMAND_SET_INTELLIGENT_ANALYSIS_OBJ_ALIAS_SAVE         (COMMAND_SET_DO_ZERO_TIME_INTERVAL + 1)  //智能分析别名保存
#define COMMAND_SET_DSP_OBSERVE_MODE							(COMMAND_SET_INTELLIGENT_ANALYSIS_OBJ_ALIAS_SAVE+1)//设置观察模式 0 默认观察模式 1极限性能模式

#define	COMMAND_SET_FOCUS_NEAR_ONE_STEP							(COMMAND_SET_DSP_OBSERVE_MODE+1)//聚焦单步
#define	COMMAND_SET_FOCUS_FAR_ONE_STEP							(COMMAND_SET_FOCUS_NEAR_ONE_STEP+1)//聚焦单步
#define COMMAND_SET_DSP_ZOOM_LARGE_ONE_STEP						(COMMAND_SET_FOCUS_FAR_ONE_STEP+1) //变倍单步
#define COMMAND_SET_DSP_ZOOM_SHRINK_ONE_STEP					(COMMAND_SET_DSP_ZOOM_LARGE_ONE_STEP+1) //变倍单步
#define COMMAND_SET_DSP_AF_AFTER_ZOOM							(COMMAND_SET_DSP_ZOOM_SHRINK_ONE_STEP+1) //变倍后是否自动聚焦
#define COMMAND_SET_DSP_COLOR_BAR_SHOW							(COMMAND_SET_DSP_AF_AFTER_ZOOM+1) //是否显示色标 0不显示，1显示
#define COMMAND_SET_DSP_LENSZOOM_EZOOM_SWITCH					(COMMAND_SET_DSP_COLOR_BAR_SHOW+1) //光学变倍和电子变倍联动0关，1开
#define COMMAND_SET_DSP_CROSS_ATTRIBUTE							(COMMAND_SET_DSP_LENSZOOM_EZOOM_SWITCH+1) //设置十字光标   长  宽  中空  都是 U16
///////////////////////////////////////////////////////////////////////
#define	COMMAND_SET_END											20000


//程序升级
#define	COMMAND_UPDATE_DSP1_PROGRAM_DEFAULT						(COMMAND_SET_END+1)
#define	COMMAND_UPDATE_DSP1_PROGRAM_NORMAL						(COMMAND_UPDATE_DSP1_PROGRAM_DEFAULT+1)
#define	COMMAND_UPDATE_DSP1_PROGRAM_BOOTLOADER					(COMMAND_UPDATE_DSP1_PROGRAM_NORMAL+1)
#define	COMMAND_UPDATE_DSP1_COMMON_DATA							(COMMAND_UPDATE_DSP1_PROGRAM_BOOTLOADER+1)
#define	COMMAND_UPDATE_DSP1_MT_PARAM_DATA						(COMMAND_UPDATE_DSP1_COMMON_DATA+1)

#define	COMMAND_TEST_DSP1_MT_PARAM_DATA							(COMMAND_UPDATE_DSP1_MT_PARAM_DATA+4) 	//测试测温数据
#define	COMMAND_SAVE_CUR_MT_PARAM_DATA							(COMMAND_TEST_DSP1_MT_PARAM_DATA+1)		//保存当前的测温数据到flash
#define	COMMAND_BAK_FLASH_MT_PARAM_DATA							(COMMAND_SAVE_CUR_MT_PARAM_DATA+1)		//备份flash中的测温数据
#define	COMMAND_LOAD_FLASH_MT_PARAM_DATA						(COMMAND_BAK_FLASH_MT_PARAM_DATA+1)		//加载flash中的测温数据
#define	COMMAND_LOAD_BAK_MT_PARAM_DATA							(COMMAND_LOAD_FLASH_MT_PARAM_DATA+1)	//读取备份的测温数据
#define	COMMAND_SET_REVISE_MF_STATUS							(COMMAND_LOAD_BAK_MT_PARAM_DATA+1)		//出厂温度修正控制
#define	COMMAND_SET_REVISE_USER_STATUS							(COMMAND_SET_REVISE_MF_STATUS+1)		//用户温度修正控制
#define COMMAND_SET_MF_TR_TABLE									(COMMAND_SET_REVISE_USER_STATUS+1)		//设置出厂温度修正
#define COMMAND_SET_USER_TR_TABLE								(COMMAND_SET_MF_TR_TABLE+1)				//设置用户温度修正
#define COMMAND_SET_MTD_PARAM									(COMMAND_SET_USER_TR_TABLE+1)			//测温参数设置
#define COMMAND_SET_MT_LENS										(COMMAND_SET_MTD_PARAM+1)				//设置镜头
#define	COMMAND_AUTO_STALL_REV									(COMMAND_SET_MT_LENS+1)


#define	COMMAND_DSP1_END										0X80000000

#if 0
#define	COMMAND_UPDATE_DSP2_PROGRAM_DEFAULT						(COMMAND_DSP1_END+1)
#define	COMMAND_UPDATE_DSP2_PROGRAM_NORMAL						(COMMAND_UPDATE_DSP2_PROGRAM_DEFAULT+1)
#define	COMMAND_UPDATE_DSP2_PROGRAM_BOOTLOADER					(COMMAND_UPDATE_DSP2_PROGRAM_NORMAL+1)
#define	COMMAND_UPDATE_DSP2_COMMON_DATA							(COMMAND_UPDATE_DSP2_PROGRAM_BOOTLOADER+1)
#define	COMMAND_SET_IP_ADDR										(COMMAND_UPDATE_DSP2_COMMON_DATA+1)
#define	COMMAND_SET_MAC_VALUE									(COMMAND_SET_IP_ADDR+1)
#endif

//////////////////////////////////
//赵伟博 命令 zs_CmdList.h COMMAND_DSP1_END之后
#define	COMMAND_UPDATE_DSP2_ROOTFS_NORMAL				(COMMAND_DSP1_END + 1)  //COMMAND_UPDATE_DSP2_PROGRAM_DEFAULT
#define COMMAND_UPDATE_DSP2_KERNEL_NORMAL 				(COMMAND_UPDATE_DSP2_ROOTFS_NORMAL + 1) //COMMAND_UPDATE_DSP2_PROGRAM_NORMAL
#define COMMAND_UPDATE_DSP2_PROGRAM_BOOTLOADER          (COMMAND_UPDATE_DSP2_KERNEL_NORMAL + 1)
#define COMMAND_UPDATE_DSP2_COMMON_DATA						(COMMAND_UPDATE_DSP2_PROGRAM_BOOTLOADER + 1)
#define COMMAND_SET_IP_ADDR														(COMMAND_UPDATE_DSP2_COMMON_DATA + 1)
#define COMMAND_SET_MAC_VALUE												(COMMAND_SET_IP_ADDR + 1)
#define COMMAND_SET_RAW_FRAME_RATE									(COMMAND_SET_MAC_VALUE + 1)
#define COMMAND_SET_VIDEO_PROFILE										(COMMAND_SET_RAW_FRAME_RATE + 1)
#define COMMAND_SET_VIDEO_BITRATE										(COMMAND_SET_VIDEO_PROFILE + 1)
#define COMMAND_SET_VIDEO_FRAME_RATE								(COMMAND_SET_VIDEO_BITRATE + 1)
#define COMMAND_SET_UART1_OUTPUT	(COMMAND_SET_VIDEO_FRAME_RATE + 1)//lk注释 透明串口
#define COMMAND_SET_REBOOT				(COMMAND_SET_UART1_OUTPUT + 1)
#define COMMAND_SET_USER_PASSWORD	(COMMAND_SET_REBOOT + 1)
#define COMMAND_SET_UART1_BAUD	(COMMAND_SET_USER_PASSWORD + 1)
#define COMMAND_GET_DEVICE_INFO                         (COMMAND_SET_UART1_BAUD + 1)
#define COMMAND_GET_ENCODE_INFO                         (COMMAND_GET_DEVICE_INFO + 1)
#define COMMAND_SET_TCP_PORT                            (COMMAND_GET_ENCODE_INFO + 1)		//from linux
#define COMMAND_SET_UDP_PORT                            (COMMAND_SET_TCP_PORT + 1)			//from linux
#define COMMAND_SET_RAW_DATA_SPEED                      (COMMAND_SET_UDP_PORT + 1)		//from linux  开启实时数据
#define COMMAND_GET_DEV_INFO                            (COMMAND_SET_RAW_DATA_SPEED + 1)
#define COMMAND_SET_LOCAL_TIME                          (COMMAND_GET_DEV_INFO + 1) //
#define COMMAND_SET_OSD_DISP_TIME							(COMMAND_SET_LOCAL_TIME + 1)
#define COMMAND_SET_OSD_DISP_DEVNAME						(COMMAND_SET_OSD_DISP_TIME + 1)
#define COMMAND_GET_FIRMWARE_INFO							(COMMAND_SET_OSD_DISP_DEVNAME + 1)
#define COMMAND_SET_FIRMWARE_INFO							(COMMAND_GET_FIRMWARE_INFO + 1)
#define COMMAND_RESTORE_DEFAULT_CONFIG						(COMMAND_SET_FIRMWARE_INFO + 1)  //复位
#define COMMAND_SET_IMAGE_CSC_ATTR							(COMMAND_RESTORE_DEFAULT_CONFIG + 1) //设置图像参数
#define COMMAND_SET_IMAGE_DCI_PARAM							(COMMAND_SET_IMAGE_CSC_ATTR + 1)//
#define COMMAND_PTZ_TO_RS485								(COMMAND_SET_IMAGE_DCI_PARAM + 1)

#define COMMAND_BEGIN_UPGRADE								(COMMAND_PTZ_TO_RS485 + 1)
#define COMMAND_STOP_UPGRADE								(COMMAND_BEGIN_UPGRADE + 1)
#define COMMAND_GET_VIDEO_CONFIG							(COMMAND_STOP_UPGRADE + 1)
#define COMMAND_GET_VIDEO_CONFIG_SUB						(COMMAND_GET_VIDEO_CONFIG + 1)
#define COMMAND_GET_IMAGE_CONFIG							(COMMAND_GET_VIDEO_CONFIG_SUB + 1)
#define COMMAND_GET_RAW_FRAME_CONFIG                        (COMMAND_GET_IMAGE_CONFIG +1 )
#define COMMAND_GET_OSD_CONFIG								(COMMAND_GET_RAW_FRAME_CONFIG + 1)
#define COMMAND_SET_BITRATE_MODE							(COMMAND_GET_OSD_CONFIG + 1)
#define COMMAND_SET_JPEG_RESOLUTION						    (COMMAND_SET_BITRATE_MODE + 1)
#define COMMAND_SET_UART2_BAUD                              (COMMAND_SET_JPEG_RESOLUTION + 1)
#define COMMAND_SET_UART_ATTR                               (COMMAND_SET_UART2_BAUD + 1 )
#define COMMAND_GET_CRUISE_PATH                             (COMMAND_SET_UART_ATTR + 1) //获取巡航路径
#define COMMAND_SET_CRUISE_PATH                             (COMMAND_GET_CRUISE_PATH + 1)//设置巡航路径
#define COMMAND_DO_CRUISE_PATH                              (COMMAND_SET_CRUISE_PATH + 1)//设置巡航路径
#define COMMAND_GET_PC_DATA                                 (COMMAND_DO_CRUISE_PATH + 1)//获取私有数据
#define COMMAND_SET_PC_DATA                                 (COMMAND_GET_PC_DATA + 1)//设置私有数据
#define COMMAND_GET_CRUISE_STATE                            (COMMAND_SET_PC_DATA + 1)//获取巡航状态
#define COMMAND_SET_DEVICE_NAME                             (COMMAND_GET_CRUISE_STATE + 1)//设置设备名称
#define COMMAND_SET_DEV_INFO                            (COMMAND_SET_DEVICE_NAME + 1)//
#define COMMAND_WRITE_FILE_TO_SD                        (COMMAND_SET_DEV_INFO + 1)//
#define COMMAND_READ_FILE_FROM_SD                       (COMMAND_WRITE_FILE_TO_SD + 1)//
#define COMMAND_WRITE_DATA_TO_RS232                     (COMMAND_READ_FILE_FROM_SD + 1)//
#define COMMAND_WRITE_DATA_TO_RS485                     (COMMAND_WRITE_DATA_TO_RS232 + 1)//
#define COMMAND_SET_KoreanShinwoo                       (COMMAND_WRITE_DATA_TO_RS485 + 1) //韩国 定制协议
#define COMMAND_SET_PRESET_MARKER                       (COMMAND_SET_KoreanShinwoo + 1) //预置点关联标记，json文件保存
#define COMMAND_DELETE_PRESET_MARKER                    (COMMAND_SET_PRESET_MARKER + 1) //删除json文件 预留未使用
#define COMMAND_GET_ALL_PRESET_NAMES                     (COMMAND_DELETE_PRESET_MARKER + 1) //获取所有预置点命名
#define COMMAND_PTZ_TO_RS232                            (COMMAND_GET_ALL_PRESET_NAMES + 1) //发送Rs232串口命令
#define COMMAND_SET_DATA_STREAM_ATTR                    (COMMAND_PTZ_TO_RS232 + 1) 	//设置流属性,启动，关闭
#define COMMAND_STARTUP_UDP_THREAD                      (COMMAND_SET_DATA_STREAM_ATTR + 1) 	//启动UDP线程 三所
#define COMMAND_SET_GE_HEATING_ATTR                     (COMMAND_STARTUP_UDP_THREAD + 1)    //设置 加热器
#define COMMAND_GET_GE_HEATING_ATTR                     (COMMAND_SET_GE_HEATING_ATTR + 1)   //获取 加热器
#define COMMAND_SET_STREAM_NAME                     	(COMMAND_GET_GE_HEATING_ATTR + 1)   //设置stream name  变更为json
#define COMMAND_GET_STREAM_NAME                     	(COMMAND_SET_STREAM_NAME + 1)       //获取stream name  变更为json
#define COMMAND_GET_RUNTIME_INFO					    (COMMAND_GET_STREAM_NAME + 1)   //获取运行时信息
#define COMMAND_GET_START_TIMESTAMP				        (COMMAND_GET_RUNTIME_INFO + 1)	//获取起始帧时间戳
#define COMMAND_SET_PTZSCHEDULE					(COMMAND_GET_START_TIMESTAMP + 1)   //定时巡检策略
#define COMMAND_GET_PTZSCHEDULE					(COMMAND_SET_PTZSCHEDULE + 1)       //定时巡检策略
#define COMMAND_SET_SND_TIMEOUT					(COMMAND_GET_PTZSCHEDULE + 1)	     //设置发送数据包延时大小 最低50ms 
#define COMMAND_SET_ONVIFALARM					(COMMAND_SET_SND_TIMEOUT + 1)
#define COMMAND_GET_ONVIFALARM					(COMMAND_SET_ONVIFALARM + 1)
#define COMMAND_GET_DEVTYPE_NAME                    (COMMAND_GET_ONVIFALARM + 1)
//#define COMMAND_SET_AUTO_FOCUS                     (COMMAND_GET_DEVTYPE_NAME + 1)
#define COMMAND_SET_DEVICE_STOPQUERY                           (COMMAND_GET_DEVTYPE_NAME + 1) 	//
#define COMMAND_GET_LRF_DIASTIMETER_STAT                    (COMMAND_SET_DEVICE_STOPQUERY + 1)
#define COMMAND_GET_COOLING_WORKTIME                    (COMMAND_GET_LRF_DIASTIMETER_STAT + 1)
#define COMMAND_SET_LOCALGPS                    (COMMAND_GET_COOLING_WORKTIME + 1)
#define COMMAND_GET_LOCALGPS                    (COMMAND_SET_LOCALGPS + 1)

#define	COMMAND_DSP2_CUSTOM										0X80000100

//申昊定制项目协议
#define COMMAND_SET_ENCODE_JPEG								(COMMAND_DSP2_CUSTOM + 1)
#define COMMAND_GET_JPEG									(COMMAND_SET_ENCODE_JPEG + 1)
#define COMMAND_HEARTBEAT_PACKET							(COMMAND_GET_JPEG + 1)
#define COMMAND_SYNC_DSP                                    (COMMAND_HEARTBEAT_PACKET + 1)

/////////////////////////////////////////////
#define	COMMAND_IphoneApp	  0X80001100
#define COMMAND_setPalette    (COMMAND_IphoneApp + 1)
#define COMMAND_setZoom       (COMMAND_setPalette + 1)

#define	COMMAND_FROM_APP                        0X80001100
#define COMMAND_APP_SET_PALETTE                 (COMMAND_FROM_APP + 1)
#define COMMAND_APP_SET_ZOOM                    (COMMAND_APP_SET_PALETTE + 1)
#define COMMAND_APP_GET_CAMERA                  (COMMAND_APP_SET_ZOOM + 1)
#define COMMAND_APP_GET_DEVCONFIG               (COMMAND_APP_GET_CAMERA + 1)
#define COMMAND_APP_SET_SHARPNESS               (COMMAND_APP_GET_DEVCONFIG + 1)
#define COMMAND_APP_SET_BRIGHTNESS              (COMMAND_APP_SET_SHARPNESS + 1)
#define COMMAND_APP_SET_CONTRAST                (COMMAND_APP_SET_BRIGHTNESS + 1)
#define COMMAND_APP_SET_NOISEREDUCTION          (COMMAND_APP_SET_CONTRAST + 1)
#define COMMAND_APP_SET_RETICLE                 (COMMAND_APP_SET_NOISEREDUCTION + 1)
#define COMMAND_APP_SET_XCORDINATE              (COMMAND_APP_SET_RETICLE + 1)
#define COMMAND_APP_SET_YCORDINATE              (COMMAND_APP_SET_XCORDINATE + 1)
#define COMMAND_APP_SET_GPSENABLE               (COMMAND_APP_SET_YCORDINATE + 1)
#define COMMAND_APP_SET_TRACEENABLE             (COMMAND_APP_SET_GPSENABLE + 1)
#define COMMAND_APP_SET_DISTANCEENABLE          (COMMAND_APP_SET_TRACEENABLE + 1)
#define COMMAND_APP_UPGRADE                     (COMMAND_APP_SET_DISTANCEENABLE+1)
#define COMMAND_APP_REBOOT                      (COMMAND_APP_UPGRADE + 1)
#define COMMAND_APP_GET_ANALYSERESULT           (COMMAND_APP_REBOOT + 1)
#define COMMAND_APP_SET_PIP                     (COMMAND_APP_GET_ANALYSERESULT + 1)
#endif /* ZS_CMDLIST_H_ */

//asd.mp3
